spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false
  sql:
    init:
      mode: never
jwt:
  secret: iimxlU5IZxO+N4VaQVoVpKzTnE63eqCRyhm9UKcZirk=
service:
  user: http://localhost:8080/mock/users
  ride: http://localhost:8080/mock/rides
  driver: http://localhost:8080/mock/drivers