spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/request_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: never
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  redis:
    host: localhost
    port: 6379
server:
  port: 8081
jwt:
  secret: iimxlU5IZxO+N4VaQVoVpKzTnE63eqCRyhm9UKcZirk=
  expiration: 86400000
service:
  user: http://localhost:8080/mock/users
  ride: http://localhost:8080/mock/rides
  driver: http://localhost:8080/mock/drivers
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    com.gdc.requests_management: DEBUG