apiVersion: v1
kind: ConfigMap
metadata:
  name: request-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/gdc_db
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
  SERVICE_USER: http://user-service:8080/api/users
  SERVICE_RIDE: http://ride-service:8080/api/rides
  SERVICE_DRIVER: http://driver-service:8080/api/drivers
  # Admin configuration
  ADMIN_USERNAME: admin
  ADMIN_EMAIL: admin@gdc.com
  DEFAULT_ADMIN_USERNAME: admin
  DEFAULT_ADMIN_EMAIL: admin@gdc.com
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"